### ISSUE TITLE
Failed to connect client peer, please check the configuration and peer status

### ISSUE THREAD

**Issue by smajen** [feitnomore/hyperledger-fabric-kubernetes#1]
Hi, I get this error running explorer on kubernetes, is there an issue with the configuration file?

Sync process is started for the network : [network-1] and client : [client-1]
<<<<<<<<<<<<<<<<<<<<<<<<<< Synchronizer Error >>>>>>>>>>>>>>>>>>

    >>>Error : [ 'Failed to connect client peer, please check the configuration and peer status' ]<<<

<<<<<<<<<<<<<<<<<<<<<<< Closing client processor >>>>>>>>>>>>>>>>>>

    >>>Received kill signal, shutting down gracefully<<<

<<<<<<<<<<<<<<<<<<<<<<< Closing explorer >>>>>>>>>>>>>>>>>>

    >>>Closed out connections<<<

<<<<<<<<<<<<<<<<<<<<<<< Closing client processor >>>>>>>>>>>>>>>>>>>>> 

thanks

**Comment by smajen** [comment]
Changing config.json to 'host' from 'local' gets me a bit further, I can now load the Explorer UI but it doesn't show any data. Log files have this:

[2018-12-10 17:17:07.896] [DEBUG] FabricClient - Found existing orderer grpc://orderer:PORT
[2018-12-10 17:17:07.896] [DEBUG] FabricClient - Successfully created orderer [orderer:PORT] for client [client-1]
[2018-12-10 17:17:07.896] [DEBUG] Proxy - getPeersStatus >> []
[2018-12-10 17:17:07.897] [DEBUG] Proxy - getChannels >> []
[2018-12-10 17:17:07.899] [DEBUG] Proxy - getChannelsInfo >> []

**Comment by feitnomore** [comment]
Explorer issues should be opened against Explorer repository, not mine. Not sure what you're doing. How does your config.json looks like? The config.json provided in this repository works perfectly.
Thanks.

**Comment by smajen** [comment]
they don't support kubernetes so asked me to speak to you

**Comment by feitnomore** [comment]
Sorry, I can't support the tool either, the only thing I did was creating a YAML to run the already packed version inside kubernetes. From your error, this seems to be a configuration problem.
Thanks.
