### ISSUE TITLE
How to register Explorer user

### ISSUE THREAD

**Issue by iceriverdog** [feitnomore/hyperledger-fabric-kubernetes#10]
I used the api :here.
http://127.0.0.1:8080/api/register
{
"user": "string",
"password": "string",
"affiliation": "string",
"roles": "string"
}
and the err : 401 unauthorized.

Thank you in advance!

**Comment by feitnomore** [comment]
In my guide we're not using any user auth on explorer as far as I remember, its been a while.
Anyways, for explorer questions I think you should open against them, they might be able to help you.
