### ISSUE TITLE
The connection to the server is lost

### ISSUE THREAD

**Issue by mendezthomas08** [feitnomore/hyperledger-fabric-kubernetes#3]
When I run kubectl get node ,I am getting this:The connection to the server is lost localhost:8080 was refused - did you specify the right host or port?
how can I fix this

**Comment by feitnomore** [comment]
Probably a problem with your kubernetes installation, nothing related to Hyperledger Fabric.
I would take a look at KUBECONFIG env var, and your config.yaml file.
Thanks!
