### ISSUE TITLE
Error while deploying hyperledger-explorer-app

### ISSUE THREAD

**Issue by kalesujata97** [feitnomore/hyperledger-fabric-kubernetes#8]
Hii,

C:\Users\Kale\Desktop\Hyperledger Fabric>kubectl logs blockchain-explorer-app-fcc5dd6f7-5ldpv
false 'ssl-certs' '/opt/explorer/ssl-certs'
D1213 12:28:01.320646516       6 env_linux.cc:71]            Warning: insecure environment read function 'getenv' used
D1213 12:28:02.106781276       6 env_linux.cc:71]            Warning: insecure environment read function 'getenv' used
******* Initialization started for hyperledger fabric platform ******, { 'first-network':
   { name: 'first-network',
     profile: './connection-profile/first-network.json' } }
 client_configs.name  first-network  client_configs.profile  ./connection-profile/first-network.json
FabricUtils.createFabricClient
config.client.tlsEnable  true
FabricConfig, this.config.channels  mychannel
{ Error: ENOENT: no such file or directory, open '/fabric-path/fabric-samples/first-network/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at FabricGateway._enrollUserIdentity (/opt/explorer/app/platform/fabric/gateway/FabricGateway.js:187:19)
    at FabricGateway.initialize (/opt/explorer/app/platform/fabric/gateway/FabricGateway.js:116:28)
    at <anonymous>
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/fabric-path/fabric-samples/first-network/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem' }

 ********* call to initializeDetachClient **********
initializeDetachClient --> client_config  { name: 'first-network',
  profile: './connection-profile/first-network.json' }  name  first-network
initializeDetachClient, network config)  { name: 'first-network',
  version: '1.0.0',
  license: 'Apache-2.0',
  client:
   { tlsEnable: true,
     adminUser: 'admin',
     adminPassword: 'adminpw',
     enableAuthentication: false,
     organization: 'Org1',
     connection: { timeout: [Object] } },
  channels: { mychannel: { peers: [Object], connection: [Object] } },
  organizations:
   { Org1MSP:
      { mspid: 'Org1MSP',
        fullpath: true,
        adminPrivateKey: [Object],
        signedCert: [Object] } },
  peers:
   { 'peer0.org1.example.com':
      { tlsCACerts: [Object],
        url: 'grpcs://localhost:7051',
        eventUrl: 'grpcs://localhost:7053',
        grpcOptions: [Object] } } }

************************************* initializeDetachClient *************************************************
Error : Failed to connect client peer, please check the configuration and peer status
Info :  Explorer will continue working with only DB data
************************************** initializeDetachClient ************************************************

FabricUtils.createDetachClient
initializeListener, client_name, client  first-network { name: 'first-network',
  profile: './connection-profile/first-network.json' }

Please open web browser to access ：http://localhost:8080/

pid is 6

FabricConfig, this.config.channels  mychannel
<<<<<<<<<<<<<<<<<<<<<<<<<< Explorer Error >>>>>>>>>>>>>>>>>>>>>
Error :  [ 'Default client peer is down and no channel details available database' ]
Received kill signal, shutting down gracefully
<<<<<<<<<<<<<<<<<<<<<<<<<< Closing explorer  >>>>>>>>>>>>>>>>>>>>>
Closed out connections

Thanks in advance

**Comment by feitnomore** [comment]
Looks like you've skipped some step regarding the config.json file for the explorer app.
Your application is looking for:
/fabric-path/fabric-samples/first-network/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem

If you look at my config.json example, there is no .pem file for the config.json, so you might be either skipping the creation of config.json or copying it wrongly.
It might also be a problem with the run.sh shellscript.
