### ISSUE TITLE
Unable to create channel

### ISSUE THREAD

**Issue by pranshurastogi** [feitnomore/hyperledger-fabric-kubernetes#9]
Following steps from README.md. I have encountered error at point 12.
Create a channel

`root@fabric-tools:/fabric# ls
Org1MSPanchors.tx  Org3MSPanchors.tx  channel1.tx  configtx.yaml  genesis.block
Org2MSPanchors.tx  Org4MSPanchors.tx  config       crypto-config
root@fabric-tools:/fabric# export ORDERER_URL="blockchain-orderer:31010"
root@fabric-tools:/fabric# export CORE_PEER_ADDRESSAUTODETECT="false"
root@fabric-tools:/fabric# export CORE_PEER_NETWORKID="nid1"
root@fabric-tools:/fabric# export CORE_PEER_LOCALMSPID="Org1MSP"
/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/"pto-config 
root@fabric-tools:/fabric# export FABRIC_CFG_PATH="/etc/hyperledger/fabric"
ME} -f /fabric/${CHANNEL_NAME}.tx annel create -o ${ORDERER_URL} -c ${CHANNEL_NA 
2020-01-03 03:56:50.090 -02 [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
Error: got unexpected status: SERVICE_UNAVAILABLE -- will not enqueue, consenter for this channel hasn't started yet
root@fabric-tools:/fabric# `

Do let me know how to resolve this, I am using kubectl and minikube in local.
Ubuntu 16.04
Thanking you in anticipation.

**Comment by feitnomore** [comment]
What you pasted is confusing, can you format it correctly? seems like there are multiple commands without division, missing characters, etc, etc, etc...

**Comment by nirkov** [comment]
I also have a problem creating the network.
I ran this - 
```
kubectl exec -it fabric-tools -- /bin/bash
export CHANNEL_NAME="channel1"
cd /fabric
configtxgen -profile FourOrgsChannel -outputCreateChannelTx ${CHANNEL_NAME}.tx -channelID ${CHANNEL_NAME}
export ORDERER_URL="blockchain-orderer:31010"
export CORE_PEER_ADDRESSAUTODETECT="false"
export CORE_PEER_NETWORKID="nid1"
export CORE_PEER_LOCALMSPID="Org1MSP"
export CORE_PEER_MSPCONFIGPATH="/fabric/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/"
export FABRIC_CFG_PATH="/etc/hyperledger/fabric"
peer channel create -o ${ORDERER_URL} -c ${CHANNEL_NAME} -f /fabric/${CHANNEL_NAME}.tx 
```

and got - 
`Error: failed to create deliver client: orderer client failed to connect to blockchain-orderer:31010: failed to create new connection: connection error: desc = "transport: error while dialing: dial tcp: lookup orderer on 10.96.0.10:53: no such host"`

Any suggestion?

**Comment by feitnomore** [comment]
Its always the service... when you lookup a name like that I believe you're looking up the service and not the pod itself, because, when you create a pod, there is a hash appended to it.
Anyways, looks like your orderer is not running. Any errors when starting it?
